### PR TITLE
fix docs/repos links on crates.io

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by saurvs** [comment]
Umm, it's correct the way it is??

**Comment by oli-obk** [comment]
currently the "repository" link points to your documentation and the "homepage" link points to your repository

**Comment by oli-obk** [comment]
oh, I got confused, sorry. But the "homepage" link still points to the documentation

**Comment by saurvs** [comment]
Ok that can change. Thanks!

**Pull request merged**
